In [4]:
# Load Liraries
import numpy as np
 
import keras 
from keras.preprocessing.image import ImageDataGenerator
 
"""# Import Model"""
 
model_path1 = 'tumor_or_notumor.h5'

model1 = keras.models.load_model(model_path1)
 
"""#Preprocessing"""
 
#horse==NO image path
h1 = 'brain_tumor_dataset/no/10 no.jpg'
h2 = 'brain_tumor_dataset/no/11 no.jpg'
h3 = 'brain_tumor_dataset/no/12 no.jpg'
h4 = 'brain_tumor_dataset/no/13 no.jpg'
h5 = 'brain_tumor_dataset/no/14 no.jpg'
h6 = 'brain_tumor_dataset/no/15 no.jpg'
h7 = 'brain_tumor_dataset/no/22 no.jpg'
h8 = 'brain_tumor_dataset/no/17 no.jpg'
 
#human image path
hu1 = 'brain_tumor_dataset/yes/Y100.jpg'
hu2 = 'brain_tumor_dataset/yes/Y101.jpg'
hu3 = 'brain_tumor_dataset/yes/Y102.jpg'
hu4 = 'brain_tumor_dataset/yes/Y103.jpg'
hu5 = 'brain_tumor_dataset/yes/Y104.jpg'
hu6 = 'brain_tumor_dataset/yes/Y105.jpg'
 
import numpy as np
from keras.preprocessing import image
 
def pred_human_horse(model, horse_or_human):
    test_image = image.load_img(horse_or_human, target_size = (150, 150))
    test_image = image.img_to_array(test_image)/255
    test_image = np.expand_dims(test_image, axis = 0)
 
    result = model.predict(test_image).round(3)
 
    pred = np.argmax(result)
    print(result, "--->>>", pred)
 
    if pred == 0:
        print('Predicted>>> No Tuomr')
    else:
        print('Predicted>>> Tumor')
 
"""## Predict Output"""
 
for horse_or_human in [h1,h2,h3,h4,h5,h6,h7,h8, hu1,hu2,hu3,hu4,hu5,hu6]:
    pred_human_horse(model1, horse_or_human)

[[0.266 0.734]] --->>> 1
Predicted>>> Tumor
[[0.992 0.008]] --->>> 0
Predicted>>> No Tuomr
[[0.571 0.429]] --->>> 0
Predicted>>> No Tuomr
[[0.992 0.008]] --->>> 0
Predicted>>> No Tuomr
[[0.989 0.011]] --->>> 0
Predicted>>> No Tuomr
[[0.028 0.972]] --->>> 1
Predicted>>> Tumor
[[0.933 0.067]] --->>> 0
Predicted>>> No Tuomr
[[0.583 0.417]] --->>> 0
Predicted>>> No Tuomr
[[0.476 0.524]] --->>> 1
Predicted>>> Tumor
[[0.218 0.782]] --->>> 1
Predicted>>> Tumor
[[0.13 0.87]] --->>> 1
Predicted>>> Tumor
[[0.003 0.997]] --->>> 1
Predicted>>> Tumor
[[0.108 0.892]] --->>> 1
Predicted>>> Tumor
[[0.176 0.824]] --->>> 1
Predicted>>> Tumor
